#!/bin/bash
#This is the shell script to run shadowsocksR in the background.

# Privoxy 默认监听端口是是8118
export http_proxy=http://127.0.0.1:8118
export https_proxy=http://127.0.0.1:8118
export no_proxy=localhost

# 启动服务
systemctl start privoxy.service

#启动ssr
eval $(ps -ef | grep -v grep | grep local.py | awk '{ print "kill -9 " $2 }')
nohup python /cluster/home/zhangyumeng/shadowsocksr/shadowsocks/local.py -c /cluster/home/zhangyumeng/shadowsocksr/config.json >> /cluster/home/zhangyumeng/shadowsocksr/shadowsocks/ssserver.log 2>&1 &